services:
  - type: web
    name: eduplatform-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: FIREBASE_DB_URL
        value: https://your-firebase-project.firebaseio.com
